# @Date:   2020-07-15T10:53:03+10:00
# @Last modified time: 2020-09-18T23:01:52+10:00

# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Nicolas Suzor
email: nic@suzor.com

subtitle: Law professor at QUT's Digital Media Research Centre # site tagline that appears below site title in masthead
description: >- # this means to ignore newlines until "baseurl:"
  Law professor. Expert in the governance of digital technologies. Author of <a href="https://www.amazon.com/Lawless-Secret-Rules-Govern-Digital/dp/1108740472/">Lawless: the secret rules that govern our digital lives.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
markdown: kramdown
twitter_username: nicsuzor
github_username:  nicsuzor
#remote_theme: "poole/hyde"
google_analytics: UA-4131259-1

lang: en-US
author:
  name: Nicolas Suzor
  twitter: nicsuzor
  picture: assets/Suzor-Nic-2014-square.png
logo: /assets/ns-logo-1.png
search: false

font-awesome:
  assets: true
  
plugins: # previously gems
  - jekyll-seo-tag
  - jekyll-remote-theme
  - jekyll-redirect-from
  - jekyll-font-awesome-sass
